### ISSUE TITLE
[Feature] provide distribution to use in browser

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda-sdk#15]
To facilitate use in web applications. A simple demo could be a form field to type in a notation which is then looked up and corresponding labels are shown.

**Comment by stefandesu** [comment]
You're right, this is still missing. We should bump it to version 1.0.0 before we publish it though. Is there anything that we should add or change for 1.0.0?

**Comment by nichtich** [comment]
I only found #18 and #19.

**Comment by stefandesu** [comment]
We can add #18 in a minor update and release 1.0.0 this week.

**Comment by stefandesu** [comment]
> release 1.0.0 this week.

Haha, that went well... I'm going to provide a browser distribution on Thursday, and we might be able to release 1.0.0 on Friday or next Monday. 👍

**Comment by stefandesu** [comment]
I just issued a test release (version 0.1.0) to NPM. If everything works, I'll adjust the README and we can close this. There are some minor things still missing for 1.0.0, but if this works, we can release right after everything is done.
