### ISSUE TITLE
SkosmosApi: implement getSchemes

### ISSUE THREAD

**Issue by stefandesu** [gbv/cocoda-sdk#27]
The SkosmosApi seems to work pretty well, but it should be refined, especially when it comes to getting vocabulary/scheme informationen and transforming the API results to JSKOS.

API documentation: http://api.finto.fi/doc/

Basically a continuation of #24.

**Comment by nichtich** [comment]
For this issue it is enough to implement getSchemes based on [/vocabularies](http://api.finto.fi/doc/#!/Global32methods/get_vocabularies).

**Comment by stefandesu** [comment]
`getSchemes` now loads additional information about given vocabularies (usually just the prefLabel). Note that we still need a list of vocabularies with URIs and `VOCID`.
