### ISSUE TITLE
Reduce bundle size

### ISSUE THREAD

**Issue by stefandesu** [gbv/cocoda-sdk#28]
We should aim to reduce the bundle size. Some specific ideas:
- [ ] Require some packages to be included separately (for example, if a page uses both jskos-tools and cocoda-sdk, jskos-tools would basically be added twice because it is included in cocoda-sdk)
- [ ] Reduce or eliminate Lodash usage
- [ ] Maybe offer the local mappings provider as a separate package because it requires localForage and uuid. This would drastically reduce the bundle size if local mappings are not necessary (which should actually be the case for most people, right?)

Find cocoda-sdk's current bundle size [here](https://bundlephobia.com/result?p=cocoda-sdk). (At the time of writing: 128.5 kB minified, 40.5 kB minified + gzipped.)

(Adding this to the 2.0.0 milestone because removing local mappings would be a breaking change.)

**Comment by nichtich** [comment]
We could split into individual packages for providers, e.g.

* cocoda-sdk-local
* cocoda-sdk-skohub
* ...

Should each be put in an individual git repository or bundle them here?

**Comment by stefandesu** [comment]
I thought maybe we could bundle it here, but release them as separate packages.

If used in a browser, I'm a bit unsure how we should deal with dependencies though. 🤔

**Comment by stefandesu** [comment]
I'm currently rewriting cocoda-sdk as an ES module which will allow us to use tree shaking to reduce the total bundle size when not everything is needed.

> Require some packages to be included separately (for example, if a page uses both jskos-tools and cocoda-sdk, jskos-tools would basically be added twice because it is included in cocoda-sdk)

I would still do this for the browser bundle. The question is whether we should only exclude jskos-tools or other dependencies as well.

> Reduce or eliminate Lodash usage

Still relevant in my opinion, but requires some work.

> We could split into individual packages for providers

In theory, we could split the providers off and offer them as separate files for the browser bundle. However, since tree shaking is a thing and it's not an issue if you used Node, I'd say we don't need to do this.

**Comment by stefandesu** [comment]
I started replacing Lodash usage and noticed that it doesn't really reduce bundle size at all. Since the included Lodash methods are also tree-shaken, they add fairly little to the bundle.

For the browser bundle, we could still externalize some of the dependencies, but we can do that at a later point.
