### ISSUE TITLE
Add LOC vocabularies provider

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda-sdk#32]
[LCSH](https://id.loc.gov/authorities/subjects.html) and other vocabularies at https://id.loc.gov/ should be accessible via cocoda-sdk. Is there an API?

**Comment by stefandesu** [comment]
Some helpful links:
- https://id.loc.gov/techcenter/
- https://labs.loc.gov/lc-for-robots/
- https://libraryofcongress.github.io/data-exploration/ (this is, as I understand it, the official API; however, it is still in beta, that's why you can't find it on the official homepage yet)

**Comment by stefandesu** [comment]
Experimental support to acccess LCSH and LCNAF is available since [v1.0.13](https://github.com/gbv/cocoda-sdk/releases/tag/v1.0.13).

**Comment by nichtich** [comment]
Implementation revealed a bug in the LoC-API backend. This issue can be closed when the bug has been resolved.

**Comment by stefandesu** [comment]
It's fixed according to my email contact. They are also looking into a suggest service for LCC, but that's a separate issue.
